version: "3.2"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thtxyyx
      MYSQL_PASSWORD: rtyyxksl
      MYSQL_DATABASE: democredit
      MYSQL_USER: democredit
    ports:
      - 3306:3306
  server:
    build: .
    # depends_on:
    #   - db
    environment:
      - PORT=9898
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=democredit
      - DB_PASSWORD=rtyyxksl
      - DB_NAME=democredit
      - JWT_SECRET=kqfjifjfmfkmffmfmomf2mmof2o
      - PAYSTACK_PRIVATE_KEY=sk_test_d90eb2d7f307f3f67bb59e4c3dc334d003bb8d87

    ports:
      - 9898:9898

volumes:
  db:
    driver: local
